# Default values for jenkins.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry-8b60bc8e-3ca3-44f7-af77-9982fb7cc09a.dyn.mayope.net/todolist
  pullPolicy: Always
  version: latest

serviceAccount:
  # Specifies whether a service account should be created
  create: true


service:
  type: ClusterIP
  port: 8080
  healthCheckPath: /actuator/health/liveness

ingress:
  enabled: true
