spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: username
    password: password

project:
  description: todoapp

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

