{{- $svcPort := .Values.service.port -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "service.serviceAccountName" . }}
      imagePullSecrets:
        - name: docker-registry-auth
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $svcPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.service.healthCheckPath }}
              port: http
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 100
          readinessProbe:
            httpGet:
              path: {{ .Values.service.healthCheckPath }}
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 100
          resources:
            requests:
              memory: 1G
              cpu: 1
            limits:
              memory: 1G
              cpu: 1
