{{- if .Values.ingress.enabled -}}
  {{- $fullName := include "service.fullname" . -}}
  {{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ $fullName }}"
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  rules:
    - host: todo-47afbadd-701b-47fc-88e0-d108a390294a.dyn.mayope.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
{{- end }}
